<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fbp</string>
	</array>

	<key>name</key>
	<string>FBP</string>

	<key>injectionSelector</key>
	<string>L:source.js -comment -string -text</string>
	
	<key>patterns</key>
	<array>
		<!-- Injected block for `/* fbp */` -->
		<dict>
			<key>name</key>
			<string>fbp.embedded.block</string>
			<key>begin</key>
			<string>`(?=\s*#\s*fbp\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fbp</string>
				</dict>
			</array>
		</dict>
		
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#legacy_export_public_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#legacy_export_private_name_port</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#legacy_export_private_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#legacy_export_assignment_operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#legacy_export_statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#export_public_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#export_node_port</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#export_node</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#export_assignment_operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inport_statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#outport_statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#right_port</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#connection</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#left_port</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#node</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#iip</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single-line comment.</string>
			<key>match</key>
			<string>((#).*)</string>
		</dict>
		<key>connection</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.fbp</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.fbp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fbp</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Connection.</string>
			<key>match</key>
			<string>(?:([a-zA-Z0-9_]+\()(?:([a-zA-Z\/\-0-9_]+)|([a-zA-Z\/\-0-9_]+)\:|([a-zA-Z\/\-0-9_]+)\:([a-zA-Z\/=_,0-9]+))?(\))\s(?:([A-Z\.0-9_]+)\[([0-9])\]|([A-Z\.0-9_]+))|(\'(?:\\\'|[^'])*\'))\s(-&gt;)</string>
		</dict>
		<key>export_assignment_operator</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Export assignment operator.</string>
			<key>match</key>
			<string>^((?:IN|OUT)PORT)(=)</string>
		</dict>
		<key>export_node</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Export node.</string>
			<key>match</key>
			<string>^((?:IN|OUT)PORT)(=)([A-Za-z0-9_]+)</string>
		</dict>
		<key>export_node_port</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Export node port.</string>
			<key>match</key>
			<string>^((?:IN|OUT)PORT)(=)([A-Za-z0-9_]+)\.([A-Z0-9_]+)</string>
		</dict>
		<key>export_public_name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Export public name.</string>
			<key>match</key>
			<string>^((?:IN|OUT)PORT)(=)([A-Za-z0-9_]+)\.([A-Z0-9_]+):([A-Z0-9_]+)</string>
		</dict>
		<key>iip</key>
		<dict>
			<key>comment</key>
			<string>Initial information packet.</string>
			<key>match</key>
			<string>(\'(?:\\\'|[^'])*\')</string>
			<key>name</key>
			<string>string.quoted.single.fbp</string>
		</dict>
		<key>inport_statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>INPORT statement.</string>
			<key>match</key>
			<string>^(INPORT)</string>
		</dict>
		<key>left_port</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.fbp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fbp</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Port on the left hand side of a connection.</string>
			<key>match</key>
			<string>([a-zA-Z0-9_]+\()(?:([a-zA-Z\/\-0-9_]+)|([a-zA-Z\/\-0-9_]+)\:|([a-zA-Z\/\-0-9_]+)\:([a-zA-Z\/=_,0-9]+))?(\))\s(?:([A-Z\.0-9_]+)\[([0-9])\]|([A-Z\.0-9_]+))</string>
		</dict>
		<key>legacy_export_assignment_operator</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Legacy export assignment operator.</string>
			<key>match</key>
			<string>^(EXPORT)(=)</string>
		</dict>
		<key>legacy_export_private_name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Legacy export private name.</string>
			<key>match</key>
			<string>^(EXPORT)(=)([A-Za-z0-9_]+)</string>
		</dict>
		<key>legacy_export_private_name_port</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Legacy export private name port.</string>
			<key>match</key>
			<string>^(EXPORT)(=)([A-Za-z0-9_]+)\.([A-Za-z\.0-9_]+)</string>
		</dict>
		<key>legacy_export_public_name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Legacy export public name.</string>
			<key>match</key>
			<string>^(EXPORT)(=)([A-Za-z0-9_]+)\.([A-Za-z\.0-9_]+):([A-Z0-9_]+)</string>
		</dict>
		<key>legacy_export_statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Legacy EXPORT statement.</string>
			<key>match</key>
			<string>^(EXPORT)</string>
		</dict>
		<key>node</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.fbp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Node.</string>
			<key>match</key>
			<string>([a-zA-Z0-9_]+\()(?:([a-zA-Z\/\-0-9_]+)|([a-zA-Z\/\-0-9_]+)\:|([a-zA-Z\/\-0-9_]+)\:([a-zA-Z\/=_,0-9]+))?(\))</string>
		</dict>
		<key>outport_statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>OUTPORT statement.</string>
			<key>match</key>
			<string>^(OUTPORT)</string>
		</dict>
		<key>right_port</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.fbp</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fbp</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fbp</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.fbp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fbp</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fbp</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>storage.type.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Port on the right hand side of a connection.</string>
			<key>match</key>
			<string>(?:([a-zA-Z0-9_]+\()(?:([a-zA-Z\/\-0-9_]+)|([a-zA-Z\/\-0-9_]+)\:|([a-zA-Z\/\-0-9_]+)\:([a-zA-Z\/=_,0-9]+))?(\))\s(?:([A-Z\.0-9_]+)\[([0-9])\]|([A-Z\.0-9_]+))|(\'(?:\\\'|[^'])*\'))\s(-&gt;)\s(?:([A-Z\.0-9_]+)\[([0-9])\]|([A-Z\.0-9_]+))</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fbp</string>
	<key>uuid</key>
	<string>f452d01c-8d15-451a-ba55-cc6e8bd96bd8</string>
</dict>
</plist>
